const initialProblems = [
  // Easy
  {
    id: 1,
    name: "Build Array from Permutation",
    difficulty: "Easy",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 2,
    name: "Concatenation of Array",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: true,
  },
  {
    id: 3,
    name: "Running Sum of 1d Array",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: false,
  },
  {
    id: 4,
    name: "Richest Customer Wealth",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: true,
  },
  {
    id: 5,
    name: "Shuffle the Array",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: false,
  },
  {
    id: 6,
    name: "Kids With the Greatest Number of Candies",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: false,
  },
  {
    id: 7,
    name: "Number of Good Pairs",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: false,
  },
  {
    id: 8,
    name: "How Many Numbers Are Smaller Than Current",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: false,
  },
  {
    id: 9,
    name: "Create Target Array",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: false,
  },
  {
    id: 10,
    name: "Check if Sentence Is Pangram",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: false,
  },
  {
    id: 11,
    name: "Count Items Matching Rule",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: false,
  },
  {
    id: 12,
    name: "Find Highest Altitude",
    difficulty: "Easy",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 13,
    name: "Flipping an Image",
    difficulty: "Easy",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 14,
    name: "Cells with Odd Values",
    difficulty: "Easy",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 15,
    name: "Matrix Diagonal Sum",
    difficulty: "Easy",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 16,
    name: "Find Numbers with Even Digits",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: false,
  },
  {
    id: 17,
    name: "Transpose Matrix",
    difficulty: "Easy",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 18,
    name: "Add to Array-Form Integer",
    difficulty: "Easy",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 19,
    name: "Maximum Population Year",
    difficulty: "Easy",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 20,
    name: "Matrix Rotation Check",
    difficulty: "Easy",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 21,
    name: "Two Sum",
    difficulty: "Easy",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 22,
    name: "Find N Unique Integers Sum Zero",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: false,
  },
  {
    id: 23,
    name: "Lucky Number in Matrix",
    difficulty: "Easy",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 24,
    name: "Maximum Subarray",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: false,
  },
  {
    id: 25,
    name: "Reshape Matrix",
    difficulty: "Easy",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 26,
    name: "Plus One",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: false,
  },
  {
    id: 27,
    name: "Remove Duplicates",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: false,
  },
  {
    id: 28,
    name: "Minimum Cost to Move Chips",
    difficulty: "Easy",
    done: false,
    date: "",
    revision: false,
  },

  // Medium
  {
    id: 29,
    name: "Spiral Matrix",
    difficulty: "Medium",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 30,
    name: "Spiral Matrix II",
    difficulty: "Medium",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 31,
    name: "Spiral Matrix III",
    difficulty: "Medium",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 32,
    name: "Set Matrix Zeroes",
    difficulty: "Medium",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 33,
    name: "Product of Array Except Self",
    difficulty: "Medium",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 34,
    name: "Find First and Last Position",
    difficulty: "Medium",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 35,
    name: "Jump Game",
    difficulty: "Medium",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 36,
    name: "Rotate Array",
    difficulty: "Medium",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 37,
    name: "Sort Colors",
    difficulty: "Medium",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 38,
    name: "House Robber",
    difficulty: "Medium",
    done: false,
    date: "",
    revision: false,
  },

  // Hard
  {
    id: 39,
    name: "Max Value of Equation",
    difficulty: "Hard",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 40,
    name: "First Missing Positive",
    difficulty: "Hard",
    done: false,
    date: "",
    revision: false,
  },
  {
    id: 41,
    name: "Good Array",
    difficulty: "Hard",
    done: false,
    date: "",
    revision: false,
  },
];

const initialProblems = [
  {
    id: 1,
    name: "Build Array from Permutation",
    difficulty: "Easy",
    done: false,
    date: "",
    revision: false,
    link: "https://leetcode.com/problems/build-array-from-permutation/",
  },
  {
    id: 2,
    name: "Concatenation of Array",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: true,
    link: "https://leetcode.com/problems/concatenation-of-array/",
  },
  {
    id: 3,
    name: "Running Sum of 1d Array",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: false,
    link: "https://leetcode.com/problems/running-sum-of-1d-array/",
  },
  {
    id: 4,
    name: "Two Sum",
    difficulty: "Easy",
    done: false,
    date: "",
    revision: false,
    link: "https://leetcode.com/problems/two-sum/",
  },
  {
    id: 5,
    name: "Maximum Subarray",
    difficulty: "Easy",
    done: true,
    date: "",
    revision: false,
    link: "https://leetcode.com/problems/maximum-subarray/",
  },
  {
    id: 6,
    name: "Spiral Matrix",
    difficulty: "Medium",
    done: false,
    date: "",
    revision: false,
    link: "https://leetcode.com/problems/spiral-matrix/",
  },
  {
    id: 7,
    name: "Product of Array Except Self",
    difficulty: "Medium",
    done: false,
    date: "",
    revision: false,
    link: "https://leetcode.com/problems/product-of-array-except-self/",
  },
  {
    id: 8,
    name: "First Missing Positive",
    difficulty: "Hard",
    done: false,
    date: "",
    revision: false,
    link: "https://leetcode.com/problems/first-missing-positive/",
  },
];